# Generated by Django 4.2 on 2023-10-31 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_message_is_read_delete_messagereadstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
