# Generated by Django 4.2 on 2023-11-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_delete_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_documents/'),
        ),
        migrations.AddField(
            model_name='message',
            name='gift',
            field=models.FileField(blank=True, null=True, upload_to='chat_gifts/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
