# Generated by Django 4.2 on 2023-08-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sociallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dating_goal',
        ),
    ]
