# Generated by Django 4.2 on 2023-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_status_content_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
