# Generated by Django 4.2 on 2023-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_status_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
