# Generated by Django 4.2 on 2023-08-10 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_alter_profile_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment_Status',
            new_name='StatusComment',
        ),
        migrations.AddField(
            model_name='status',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
