# Generated by Django 4.2 on 2023-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_status_likes_count_statuslike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
