# Generated by Django 4.2 on 2023-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_status_comments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following_set', to='account.status'),
        ),
        migrations.AddField(
            model_name='status',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends_set', to='account.status'),
        ),
    ]
