# Generated by Django 4.2 on 2023-09-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_status_followers_status_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='friends',
            field=models.ManyToManyField(blank=True, to='account.status'),
        ),
    ]
