# Generated by Django 4.2 on 2023-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_status_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
