# Generated by Django 4.2 on 2023-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_user_following'),
        ('account', '0024_statuscomment_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='status',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
