# Generated by Django 4.2 on 2023-09-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_profile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
