# Generated by Django 4.2 on 2023-09-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='night_mode',
            field=models.BooleanField(default=False),
        ),
    ]
