# Generated by Django 4.2 on 2023-09-10 08:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_profile_night_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscomment',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
