# Generated by Django 4.2 on 2023-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
