# Generated by Django 4.2 on 2023-09-18 22:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_premiumpackage_premiumpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpackage',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
