# Generated by Django 4.2 on 2023-09-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_alter_premiumpackage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='premium_until',
        ),
    ]
