# Generated by Django 4.2 on 2023-09-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_remove_profile_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
