# Generated by Django 4.2 on 2023-09-19 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0041_alter_profile_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
