# Generated by Django 4.2 on 2023-09-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_profile_liked_by_profile_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_profiles', to='account.profile'),
        ),
    ]
