# Generated by Django 4.2 on 2023-09-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_profiles', to='account.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_profiles', to='account.profile'),
        ),
    ]
