# Generated by Django 4.2 on 2023-09-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_alter_profile_liked_by_alter_profile_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='viewers',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
    ]
