# Generated by Django 4.2 on 2023-09-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_alter_profile_liked_by_alter_profile_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_cover',
            field=models.ImageField(blank=True, upload_to='users_cover/%Y/%m/%d/'),
        ),
    ]
