# Generated by Django 4.2 on 2023-09-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_profile_photo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_cover',
            field=models.ImageField(blank=True, null=True, upload_to='users_cover/%Y/%m/%d/'),
        ),
    ]
