# Generated by Django 4.2 on 2023-09-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_alter_profile_photo_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='icon_color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
