# Generated by Django 4.2 on 2023-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_remove_profile_is_active_remove_profile_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='images/affect.jpg', upload_to='users/%Y/%m/%d/'),
        ),
    ]
