# Generated by Django 4.2 on 2023-09-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_profile_photo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='account_pro_latitud_569083_idx'),
        ),
    ]
