# Generated by Django 4.2 on 2023-10-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_alter_profile_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
