# Generated by Django 4.2 on 2023-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_remove_profile_account_pro_latitud_569083_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='account.profile'),
        ),
    ]
