# Generated by Django 4.2 on 2023-12-04 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0063_profile_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='animals',
            field=models.CharField(blank=True, choices=[('Dog', 'Собака'), ('Cat', 'Кіт')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.CharField(blank=True, choices=[('No', 'Немає'), ('Yes', 'Є')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('HighSchool', 'Середня школа'), ('College', 'Коледж'), ('University', 'Університет')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='family_status',
            field=models.CharField(blank=True, choices=[('Single', 'Один'), ('Married', 'Одружений/Заміжня'), ('Divorced', 'Розлучений')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='personality_type',
            field=models.CharField(blank=True, choices=[('Introvert', 'Інтроверт'), ('Extrovert', 'Екстраверт')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('F', 'Free'), ('A', 'Attitudes'), ('E', 'Everything is difficult'), ('F', 'Free relationship')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Християнство'), ('Islam', 'Іслам')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('H', 'Hetero'), ('G', 'Gay'), ('L', 'Lesbian'), ('B', 'Bisexual'), ('A', 'Asexual'), ('D', 'Demisexual'), ('P', 'Pansexual'), ('Q', 'Queer'), ('S', 'Still searching')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_and_education',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('E', 'Employee'), ('U', 'Unemployed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('Ca', 'Capricorn'), ('Aq', 'Aquarius'), ('Pi', 'Pisces'), ('Ar', 'Aries'), ('Ta', 'Taurus'), ('Ge', 'Gemini'), ('Can', 'Cancer'), ('Le', 'Leo'), ('Vi', 'Virgo'), ('Li', 'Libra'), ('Sc', 'Scorpio'), ('Op', 'Ophiuchus'), ('Sa', 'Sagittarius')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No, I do not drink'), ('O', 'Occasionally'), ('Of', 'Often'), ('N', 'Never'), ('In', 'In the company')], max_length=2),
        ),
        migrations.CreateModel(
            name='StatusFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='account.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_statuses', through='account.StatusFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
