# Generated by Django 4.2 on 2023-12-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_languagemodel_profile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.position'),
        ),
    ]
