# Generated by Django 4.2 on 2023-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='children',
            field=models.CharField(blank=True, choices=[('S', 'Sometime in the future'), ('Iw', 'I want soon'), ('D', 'Do not want'), ('Ia', 'I already have children')], max_length=2, null=True),
        ),
    ]
