# Generated by Django 4.2 on 2023-12-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_remove_profile_family_status_alter_profile_animals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='breast_size',
        ),
    ]
