# Generated by Django 4.2 on 2023-12-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_remove_profile_breast_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='animals',
            field=models.CharField(blank=True, choices=[('C', 'Cat/cats'), ('D', 'Dog/dogs'), ('CD', 'Cats and dogs'), ('O', 'Other animals'), ('N', 'No animals')], max_length=2, null=True),
        ),
    ]
