# Generated by Django 4.2 on 2023-12-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_premiumpackage_enable_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='physique',
            field=models.CharField(blank=True, choices=[('Ec', 'Ectomorph'), ('M', 'Mesomorph'), ('En', 'Endomorph')], max_length=2),
        ),
    ]
