# Generated by Django 4.2 on 2023-12-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_alter_profile_physique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personality_type',
            field=models.CharField(blank=True, choices=[('I', 'Introvert'), ('E', 'Extrovert')], max_length=1, null=True),
        ),
    ]
