# Generated by Django 4.2 on 2023-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_alter_profile_personality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Icon Color'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
