# Generated by Django 4.2 on 2023-12-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_menuitem_title_en_menuitem_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='title_ua',
        ),
    ]
