# Generated by Django 4.2 on 2023-09-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Header Color if No Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/header_images/', verbose_name='Header Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Show Header'),
        ),
    ]
