# Generated by Django 4.2 on 2023-10-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/')),
                ('price', models.PositiveIntegerField(help_text='Price of the gift in some virtual currency or points.')),
            ],
        ),
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_bought', to=settings.AUTH_USER_MODEL)),
                ('gift_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.giftitem')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
