# Generated by Django 4.2 on 2023-10-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_giftcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftitem',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
