"""
Django settings for LoveTouch project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os,sys
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pz-q69@f7byq^#*tr)dt#h+kwrpxhs8-2tzt_d(n1bwmiqz8$!'

# Настроечные параметры Stripe
STRIPE_PUBLISHABLE_KEY = 'pk_test_51NrCynFPFVM9gK5WD8vDObiJCxfp2v3alI3KEFKoLuUgIHHwAOzk0cm7NRm1dLSSwGwNZqoaeBhyTcZsakmKzteq00aTIxcsxM' # Публикуемый ключ
STRIPE_SECRET_KEY = 'sk_test_51NrCynFPFVM9gK5W6sfMOY3xxqVoE4JTyzXopLYi7m86gcMJMnQrLTgDkzW9W4fz50TqMvmowfdxTJCOlHZd8wlf00O8cHmKJA' # Секретный ключ
STRIPE_API_VERSION = '2022-08-01'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['mysite.com',
                 '*']

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Application definition


ASGI_APPLICATION = 'LoveTouch.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
           "hosts": [('127.0.0.1', 6379)],

        },
    },
}


INSTALLED_APPS = [
    "modeltranslation",
    "daphne",
    'news.apps.NewsConfig',
    'account.apps.AccountConfig',
    'albums.apps.AlbumsConfig',
    'dating.apps.DatingConfig',
    'chat_app.apps.ChatAppConfig', 
    'social.apps.django_app.default',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.postgres',
    'social_django',
    'pages',
    'rosetta',
    'bootstrap4',
    'taggit',
    'easy_thumbnails',
    'django_filters',  
    'ckeditor',
    'ckeditor_uploader',
    'channels',
    'channels_redis',
    'cities_light',
    'notifications',
    'gift',
    
    
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'account.last_activity_middleware.LastActivityMiddleware',
    
]

ROOT_URLCONF = 'LoveTouch.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.menu',
                'account.context_processors.footer_menu',
                'account.context_processors.referer',
                'account.context_processors.global_context',
                

            ],
        },
    },
]

WSGI_APPLICATION = 'LoveTouch.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
 'default': {
 'ENGINE': 'django.db.backends.postgresql',
 'NAME': 'Site',
 'USER': 'site',
 'PASSWORD': '202020Rjrcbr',
 }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_TRANSLATION_REGISTRY = 'LoveTouch.translation'

TIME_ZONE = 'Europe/Kiev'


USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('EN')),
    ('ru', _('RU')),
    ('ua', _('UA')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale/'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    
]



# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'account.authentication.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
    
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2'
)

# Конфигурация сервера электронной почты
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'lovetouch.site@gmail.com'
EMAIL_HOST_PASSWORD = 'oufpubrqepdkujut'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'
LOGOUT_URL = 'login'


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '796475045502-taer908gkjsesv5ht1e1l3r6kqg1kks6.apps.googleusercontent.com' # ИД клиента Google
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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' # Секрет клиента Google

SOCIAL_AUTH_FACEBOOK_KEY = '2148580538807126'        # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'e9aac72eb3f9c9c63b1f2fb21cefc70a'  # App Secret

SOCIAL_AUTH_PIPELINE = [
 'social_core.pipeline.social_auth.social_details',
 'social_core.pipeline.social_auth.social_uid',
 'social_core.pipeline.social_auth.auth_allowed',
 'social_core.pipeline.social_auth.social_user',
 'social_core.pipeline.user.get_username',
 'social_core.pipeline.user.create_user',
 'account.authentication.create_profile',
 'social_core.pipeline.social_auth.associate_user',
 'social_core.pipeline.social_auth.load_extra_data',
 'social_core.pipeline.user.user_details',
]


ABSOLUTE_URL_OVERRIDES = {
 'auth.user': lambda u: reverse_lazy('user_detail',
                                    args=[u.username])
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'encoding': 'utf8',  # Важно! Установите кодировку в UTF-8
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'shop': {
        'handlers': ['file'],
        'level': 'DEBUG',
        'propagate': True,
    },
    },
}

CKEDITOR_UPLOAD_PATH = 'uploads/ckeditor/'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}

PUSHER_APP_ID = '1671683'
PUSHER_KEY = 'e656006c91669adf76ce'
PUSHER_SECRET = '992abcf1d766e8affe21'
PUSHER_CLUSTER = 'eu'


CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app"]

DEFAULT_CHARSET = 'utf-8'


CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en', 'ru', 'uk']
CITIES_LIGHT_INCLUDE_COUNTRIES = None
CITIES_LIGHT_INCLUDE_CITIES_WITHOUT_REGION = True

