# Generated by Django 4.2 on 2023-08-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_photo_album_alter_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for', to='albums.photo'),
        ),
    ]
