# Generated by Django 4.2 on 2023-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_album_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
