# Generated by Django 4.2 on 2023-09-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_photo_comments_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='photos/no_image.jpg', upload_to='photos/users/%Y/%m/%d/'),
        ),
    ]
