# Generated by Django 4.2 on 2023-09-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False, verbose_name='Show in footer menu'),
        ),
    ]
