# Generated by Django 4.2 on 2023-09-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_header_image_page_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Header Color if No Image'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Show Header'),
        ),
    ]
